# Streamlit Cloud Configuration
# This file configures your Streamlit app for cloud deployment

[server]
# Production settings
headless = true
port = 8501
address = "0.0.0.0"

[browser]
# Prevent browser auto-opening in cloud
gatherUsageStats = false

[theme]
# Optional: customize your app's appearance
primaryColor = "#00D4AA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
# Development settings
developmentMode = false
suppressDeprecationWarnings = true
