# Streamlit Secrets Template
# Copy this to .streamlit/secrets.toml and add your real values

# API Keys (replace with real values)
ALPHA_VANTAGE_KEY = "demo"
FINNHUB_KEY = "your_finnhub_key_here"

# Database (if using cloud database)
# DB_URL = "postgresql://user:pass@host:port/db"

# Trading Configuration
# PAPER_TRADING_INITIAL_USD = 10000
# PAPER_TRADING_INITIAL_INR = 100000
# PAPER_TRADING_INITIAL_MYR = 10000

# Note: In Streamlit Cloud, add these in the app settings under "Secrets"
# Format:
# [secrets]
# ALPHA_VANTAGE_KEY = "your_real_key"
